name: Process Deployment Queue

on:
  schedule:
    # Runs every 30 minutes from 9 AM to 5 PM (NL time) from Monday to Friday
    - cron: "0,30 8-16 * * 1-5"  # Adjusted for CET/CEST timezone (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-queue:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Git user identity
      - name: Set up Git user
        run: |
          git config --global user.name "Ysoll"
          git config --global user.email "voda.cristian94@gmail.com"

      # Step 3: Configure Git to use GITHUB_TOKEN for authentication
      - name: Set up Git authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      # Step 4: Read queue and get the first RC branch (FIFO)
      - name: Read queue and get the first RC branch
        id: get_queue
        run: |
          if [ ! -s rc_queue.json ]; then
            echo "No branches in the queue"
            exit 0
          fi
          queue_branch=$(jq -r '.queue[0]' rc_queue.json)
          echo "Picked branch: $queue_branch"
          echo "::set-output name=branch::$queue_branch"

      # Step 5: Sync RC branch with master and pull latest changes before pushing
      - name: Sync RC branch with master and pull latest changes
        id: merge_master
        run: |
          branch="${{ steps.get_queue.outputs.branch }}"
          set +e  # Disable automatic exit on error

          # Fetch all remote branches
          git fetch origin

          # Check if the branch exists locally, create it if not
          if git show-ref --verify --quiet refs/heads/$branch; then
            echo "Branch $branch exists, checking it out."
            git checkout $branch

            # Pull the latest changes from the remote branch before pushing
            git pull --rebase origin $branch || exit 1
          else
            echo "Branch $branch does not exist, creating it."
            git checkout -b $branch
          fi

          # Push the branch to remote
          git push origin $branch || exit 1
          
          # Merge master into the branch
          git fetch origin master
          git merge origin/master --no-edit

          if [ $? -ne 0 ]; then
            echo "Merge conflict detected in branch: $branch, aborting."
            echo "::set-output name=conflict::true"
            exit 1  # Exit with error code to indicate a failure
          else
            echo "::set-output name=conflict::false"
          fi
        continue-on-error: true  # Allow the workflow to continue even if there's an error
